# 1.1 Create a Vector

In [3]:
# Load a Lib
import numpy as np

# Create a vector as a row
vector_row = np.array([1, 2, 3])

# Create a vector as a column
vector_column = np.array([[1],
                         [2],
                         [3]])

# 1.2 Create a Matrix

In [4]:
# Load a Lib
import numpy as np

# Creating a 2,3 Matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
matrix.shape

(2, 3)

# 1.3 Create a Sparse Matrix

In [16]:
# Load a Lib
import numpy as np
from scipy import sparse

# Create a matrix
matrix = ([[6, 0, 1],
           [0, 7, 0],
           [0, 0, 8]])

# Create a compressed Sparse row(CSR) Matrix
matrix_sparce = sparse.csr_matrix(matrix)

print(matrix_sparce)

  (0, 0)	6
  (0, 2)	1
  (1, 1)	7
  (2, 2)	8


# 1.4 Select Elements

In [37]:
# Load a Lib
import numpy as np

# Create a row vector
vector = np.array([1, 2, 3, 4, 5, 6])

print('3rd Element:', vector[2])

# Create a Matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print('2nd Row 1st Element:', matrix[1,0])

# Select all the vector elements
print('Select all the vector elements:', vector[:])

# Select first three vector elements
print('Select first three vector elements:', vector[:3])

# Select last three vector elements
print('Select last three vector elements:', vector[3:])

# Select last vector element with negative index
print('Select last vector element with negative index:', vector[-1])

# Select only first row of the matrix
print('Select only first row of the matrix:', matrix[:1,:])

# Select only First column of the matrix
print('Select only First column of the matrix:', matrix[:, :1])

3rd Element: 3
2nd Row 1st Element: 4
Select all the vector elements: [1 2 3 4 5 6]
Select first three vector elements: [1 2 3]
Select last three vector elements: [4 5 6]
Select last vector element with negative index: 6
Select only first row of the matrix: [[1 2 3]]
Select only First column of the matrix: [[1]
 [4]
 [7]]


# 1.5 Describe a Matrix

In [43]:
# Load a Lib
import numpy as np

# Create a matrix
matrix = np.array([[1, 2, 3],
                  [4, 5, 6]])

# Shape of the Matrix
print('matrix Shape: ', matrix.shape)

# Number of elements in the matrix(row * columns)
print('Number of elements:', matrix.size)

# Dimension of the matrix
print('Dimension of the matrix:', matrix.ndim)

matrix Shape:  (2, 3)
Number of elements: 6
Dimension of the matrix: 2


# 1.6 Applying Operations to Elements

In [48]:
# Load a lib
import numpy as np

# Create a Matrix 
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Create a lambda function
add_100 = lambda i: i + 100

# create a vectorized function
vectorized_100function = np.vectorize(add_100)

# Apply this function on Matrix
print(vectorized_100function(matrix))


# Other way of doing
# Create a Matrix 
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print(matrix + 100)

[[101 102 103]
 [104 105 106]
 [107 108 109]]
[[101 102 103]
 [104 105 106]
 [107 108 109]]


# 1.7 Finding the Max and Min values

In [55]:
# Load a lib
import numpy as np

# Create a matrix 
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Find a max and min
print('Max ele in Array', np.max(matrix))
print('Min ele in Array', np.min(matrix))


# Find a max and min in subset
print('Subset Max:', np.max(matrix, axis=0))
print('Subset Min:', np.max(matrix, axis=1))

Max ele in Array 9
Min ele in Array 1
Subset Max: [7 8 9]
Subset Min: [3 6 9]


In [60]:
# 1.8 Calculate Avg, Variance and Standard Deviation
# Load a lib
import numpy as np

# Create a Matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print('Mean:', np.mean(matrix))
print('Variance:', np.var(matrix))
print('Standard Deviation:', np.std(matrix))

print('Mean in each column', np.mean(matrix, axis=0))

Mean: 5.0
Variance: 6.666666666666667
Standard Deviation: 2.581988897471611
Mean in each column [4. 5. 6.]
