# 1.1 Create a Vector

In [1]:
# Load a Lib
import numpy as np

# Create a vector as a row
vector_row = np.array([1, 2, 3])

# Create a vector as a column
vector_column = np.array([[1],
                         [2],
                         [3]])

# 1.2 Create a Matrix

In [2]:
# Load a Lib
import numpy as np

# Creating a 2,3 Matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
matrix.shape

(2, 3)

# 1.3 Create a Sparse Matrix

In [3]:
# Load a Lib
import numpy as np
from scipy import sparse

# Create a matrix
matrix = ([[6, 0, 1],
           [0, 7, 0],
           [0, 0, 8]])

# Create a compressed Sparse row(CSR) Matrix
matrix_sparce = sparse.csr_matrix(matrix)

print(matrix_sparce)

  (0, 0)	6
  (0, 2)	1
  (1, 1)	7
  (2, 2)	8


# 1.4 Select Elements

In [4]:
# Load a Lib
import numpy as np

# Create a row vector
vector = np.array([1, 2, 3, 4, 5, 6])

print('3rd Element:', vector[2])

# Create a Matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print('2nd Row 1st Element:', matrix[1,0])

# Select all the vector elements
print('Select all the vector elements:', vector[:])

# Select first three vector elements
print('Select first three vector elements:', vector[:3])

# Select last three vector elements
print('Select last three vector elements:', vector[3:])

# Select last vector element with negative index
print('Select last vector element with negative index:', vector[-1])

# Select only first row of the matrix
print('Select only first row of the matrix:', matrix[:1,:])

# Select only First column of the matrix
print('Select only First column of the matrix:', matrix[:, :1])

3rd Element: 3
2nd Row 1st Element: 4
Select all the vector elements: [1 2 3 4 5 6]
Select first three vector elements: [1 2 3]
Select last three vector elements: [4 5 6]
Select last vector element with negative index: 6
Select only first row of the matrix: [[1 2 3]]
Select only First column of the matrix: [[1]
 [4]
 [7]]


# 1.5 Describe a Matrix

In [5]:
# Load a Lib
import numpy as np

# Create a matrix
matrix = np.array([[1, 2, 3],
                  [4, 5, 6]])

# Shape of the Matrix
print('matrix Shape: ', matrix.shape)

# Number of elements in the matrix(row * columns)
print('Number of elements:', matrix.size)

# Dimension of the matrix
print('Dimension of the matrix:', matrix.ndim)

matrix Shape:  (2, 3)
Number of elements: 6
Dimension of the matrix: 2


# 1.6 Applying Operations to Elements

In [6]:
# Load a lib
import numpy as np

# Create a Matrix 
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Create a lambda function
add_100 = lambda i: i + 100

# create a vectorized function
vectorized_100function = np.vectorize(add_100)

# Apply this function on Matrix
print(vectorized_100function(matrix))


# Other way of doing
# Create a Matrix 
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print(matrix + 100)

[[101 102 103]
 [104 105 106]
 [107 108 109]]
[[101 102 103]
 [104 105 106]
 [107 108 109]]


# 1.7 Finding the Max and Min values

In [7]:
# Load a lib
import numpy as np

# Create a matrix 
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Find a max and min
print('Max ele in Array', np.max(matrix))
print('Min ele in Array', np.min(matrix))


# Find a max and min in subset
print('Subset Max:', np.max(matrix, axis=0))
print('Subset Min:', np.max(matrix, axis=1))

Max ele in Array 9
Min ele in Array 1
Subset Max: [7 8 9]
Subset Min: [3 6 9]


# 1.8 Calculate Avg, Variance and Standard Deviation

In [8]:
# Load a lib
import numpy as np

# Create a Matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print('Mean:', np.mean(matrix))
print('Variance:', np.var(matrix))
print('Standard Deviation:', np.std(matrix))

print('Mean in each column', np.mean(matrix, axis=0))

Mean: 5.0
Variance: 6.666666666666667
Standard Deviation: 2.581988897471611
Mean in each column [4. 5. 6.]


# 1.9 Reshape Array 

In [9]:
# Load a Lib
import numpy as np

# Create a 3*4 Matrix
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

# Matrix Shape
print('Matrix Shpe:', matrix.shape)

# Reshape the Matrix 
matrix = matrix.reshape(2, 6)

# Matrix Shape after reshape
print('Matrix shape:', matrix.shape)

# Create a 3*4 Matrix
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

matrix = matrix.reshape(1, -1)

Matrix Shpe: (3, 4)
Matrix shape: (2, 6)


# 1.10 Transposing a Vector or Matrix

In [11]:
# Load a Lib
import numpy as np

# Create a Matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Transpose Matrix
print(matrix.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


# 1.11 Flattening a Matrix

In [14]:
# Load a Lib
import numpy as np

# Create a Matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Flattening a Matrix
print('Using Flatten method: ',matrix.flatten())

# Second method to do that
print('Using reshape method: ',matrix.reshape(1, -1))

Using Flatten method:  [1 2 3 4 5 6 7 8 9]
Using reshape method:  [[1 2 3 4 5 6 7 8 9]]


# 1.12 Rank of Matrix

In [17]:
# Load a Lib
import numpy as np

# Create a Matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Find a Rank of Matrix
print('Rank of Matrix: ', np.linalg.matrix_rank(matrix))

Rank of Matrix:  2


# 1.13 Find a determinant of Matrix

In [23]:
# Load a Lib
import numpy as np

# Create a Matrix
matrix = np.array([[1, 4, 7],
                   [2, 5, 8],
                   [3, 6, 9]])

# Determinant of Matrix
print('Determinant of Matrix: ', np.linalg.det(matrix))

Determinant of Matrix:  0.0


# 1.14 Diagonal of Matrix

In [27]:
# Load a Lib
import numpy as np

# Create a Matrix
matrix = np.array([[1, 4, 7],
                   [2, 5, 8],
                   [3, 6, 9]])

# Return Diagonal of Matrix
print('Diagonal :', matrix.diagonal())

# Return diagonal one above the main diagonal
print('Diagonal :', matrix.diagonal(offset=1))

# Return diagonal one below the main diagonal
print('Diagonal :', matrix.diagonal(offset=-1))

Diagonal : [1 5 9]
Diagonal : [4 8]
Diagonal : [2 6]


# 1.15 Trace of Matrix

In [29]:
# Load a lib
import numpy as np

# Create a Matrix
matrix = np.array([[1, 4, 7],
                   [2, 5, 8],
                   [3, 6, 9]])

# Return trace of matrix
print('Trace of Matrix using trace method: ', matrix.trace())

# Other method sum
print('sum method: ', sum(matrix.diagonal()))

Trace of Matrix using trace method:  15
sum method:  15


# 1. 16 Eigen Values and Eigen Vectors

In [31]:
# Load a lib
import numpy as np

# Create a Matrix
matrix = np.array([[1, 4, 7],
                   [2, 5, 8],
                   [3, 6, 9]])

eigen_value, eigen_vector = np.linalg.eig(matrix)

print('eigen value: ', eigen_value);
print('eigen_vector:', eigen_vector);

eigen value:  [ 1.61168440e+01 -1.11684397e+00 -1.57673427e-16]
eigen_vector: [[-0.46454727 -0.88290596  0.40824829]
 [-0.57079553 -0.23952042 -0.81649658]
 [-0.67704379  0.40386512  0.40824829]]


# 1.17 Dot products

In [32]:
# Load a lib
import numpy as np

# Create two vectors
vector_a= np.array([1, 2, 3, 4])
vector_b = np.array([4, 5, 6, 7])

# Calculate dot product
np.dot(vector_a, vector_b)


60

# 1.18 Add and Subtracting Matrix

In [33]:
# Load a lib
import numpy as np

# create two matrix
matrix_a = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

matrix_b = np.array([[1, 2, 3],
                     [4, 5, 6], 
                     [7, 8, 9]])

# Add two matrix
print('Addition: ', np.add(matrix_a, matrix_b))

# Sub two matrix
print('sub: ', np.subtract(matrix_a, matrix_b))

Addition:  [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
sub:  [[0 0 0]
 [0 0 0]
 [0 0 0]]


# 1.19 Multiply Matrix

In [37]:
# Load a lib
import numpy as np

# create two matrix
matrix_a = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

matrix_b = np.array([[1, 2, 3],
                     [4, 5, 6], 
                     [7, 8, 9]])

# Dot matrox
print('Multiply Matrix \n', matrix_a @ matrix_b)

# Element wise multiply
print('Elemenet wise Multiply \n', matrix_a * matrix_b)

Multiply Matrix 
 [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
Elemenet wise Multiply 
 [[ 1  4  9]
 [16 25 36]
 [49 64 81]]


# 1.20 Inverting a Matrix

In [42]:
# Load a lib
import numpy as np

# create two matrix
matrix_a = np.array([[1, 2],
                     [4, 5]])

# Return inverting a matrix
print('Matrix inversion \n', np.linalg.inv(matrix_a))

Matrix inversion 
 [[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]


# 1.21 Generating a Random Values

In [47]:
# Load a lib
import numpy as np

# set a seed
np.random.seed(0)

# Generate three random floats between 0.0 and 1.0
print('Random float value: \n', np.random.random(3))

# Generate three number from normal distribution with mean 0.0 and standard deviation of 1.0
print('Normal distribution: \n', np.random.normal(0.0, 1.0, 3))

Random float value: 
 [0.5488135  0.71518937 0.60276338]
Normal distribution: 
 [-2.2683282   1.33354538 -0.84272405]
